debug: false

spring.jpa.open-in-view: false

spring:
  datasource:
    url: "jdbc:postgresql://${embedded.postgresql.host}:${embedded.postgresql.port}/${embedded.postgresql.schema}"
    username: ${embedded.postgresql.user}
    password: ${embedded.postgresql.password}
  liquibase:
    rollback-file: classpath:db/migration/add-person-table/rollback-test.sql
    change-log: classpath:db/liquibase-changeLog.xml